_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
                - 75
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.11
            "6": 4.41.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 64
epochs:
    value: 3
lr:
    value: 2e-05
max_length:
    value: 512
model:
    value: /data/huangruizhi/htmlRAG/bce-reranker-base_v1
